# docker-compose.yml for a Typesense server
version: '3.8'
services:
  typesense:
    image: typesense/typesense:30.0.rca34
    container_name: typesense_search_server
    restart: unless-stopped
    ports:
      # Typesense API port
      - "8108:8108"
    volumes:
      # Persists data in a local 'typesense_data' directory
      - ./typesense_data:/data
    env_file:
      - ./.env
    environment:
      - TYPESENSE_HOST=${TYPESENSE_HOST}
      - TYPESENSE_PORT=${TYPESENSE_PORT}
      - TYPESENSE_PROTOCOL=${TYPESENSE_PROTOCOL}
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
    command:
      - '--data-dir=/data'
      - '--api-key=${TYPESENSE_API_KEY}'
      - '--listen-port=${TYPESENSE_PORT}'